apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-root-secret
                key: MYSQL_ROOT_PASSWORD            
          - name: "MYSQL_DATABASE" 
            value: "quotes_db"
          ports:
          - containerPort: 3306
            name: mysql-db
          volumeMounts:
          - name: mysql-db-persistent-storage
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-db-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-db-pv-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  labels:
    app: mysql-db
spec:
  ports:
    - port: 3306
      name: mysql-db
  selector:
    app: mysql-db

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: microk8s-hostpath
  resources:
    requests:
      storage: 120Mi
