USE quotes_db;

CREATE TABLE engels(
    id INTEGER NOT NULL AUTO_INCREMENT
    ,author VARCHAR(16)
    ,quote VARCHAR(2048)
    ,source VARCHAR(128)
    ,year SMALLINT
    , PRIMARY KEY (id)
);

INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','What is genuine is proved in the fire, what is false we shall not miss in our ranks. The opponents must grant us that youth has never before flocked to our colours in such numbers, ... in the end, one will be found among us who will prove that the sword of enthusiasm is just as good as the sword of genius.','Anti-Schelling',1841);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Political economy came into being as a natural result of the expansion of trade, and with its appearance elementary, unscientific huckstering was replaced by a developed system of licensed fraud, an entire science of enrichment.','Outlines of Political Economy',1844);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The slave frees himself when, of all the relations of private property, he abolishes only the relation of slavery and thereby becomes a proletarian; the proletarian can free himself only by abolishing private property in general.','Principles of Communism',1847);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','What is Communism? Communism is the doctrine of the conditions of the liberation of the proletariat. What is the proletariat? The proletariat is that class in society which lives entirely from the sale of its labor and does not draw profit from any kind of capital; whose weal and woe, whose life and death, whose sole existence depends on the demand for labor....','Principles of Communism',1847);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','A nation cannot become free and at the same time continue to oppress other nations. The liberation of Germany cannot therefore take place without the liberation of Poland from German oppression.','Speech on Poland',1847);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Under the freedom of trade the whole severity of the laws of political economy will be applied to the working classes. Is that to say that we are against Free Trade? No, we are for Free Trade, because by Free Trade all economical laws, with their most astounding contradictions, will act upon a larger scale, upon a greater extent of territory, upon the territory of the whole earth; and because from the uniting of all these contradictions into a single group, where they stand face to face, will result the struggle which will itself eventuate in the emancipation of the proletarians.','To Free Trade Congress at Brussels',1847);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','A few days in my old man’s factory have sufficed to bring me face to face with this beastliness, which I had rather overlooked. ..., it is impossible to carry on communist propaganda on a large scale and at the same time engage in huckstering and industry.','Letter to Marx',1845);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','A revolution is certainly the most authoritarian thing there is; it is the act whereby one part of the population imposes its will upon the other part by means of rifles, bayonets and cannon — authoritarian means, if such there be at all; and if the victorious party does not want to have fought in vain, it must maintain this rule by means of the terror which its arms inspire in the reactionists. Would the Paris Commune have lasted a single day if it had not made use of this authority of the armed people against the bourgeois? Should we not, on the contrary, reproach it for not having used it freely enough?','On Authority,',1872);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The worst thing that can befall a leader of an extreme party is to be compelled to take over a government in an epoch when the movement is not yet ripe for the domination of the class which he represents and for the realisation of the measures which that domination would imply ...','The Peasant War in Germany',1850);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The Afghans are a brave, hardy, and independent race; they follow pastoral or agricultural occupations only ... With them, war is an excitement and relief from the monotonous occupation of industrial pursuits.','On Afghanistan',1857);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Let us not, however, flatter ourselves overmuch on account of our human victories over nature. For each such victory nature takes its revenge on us. Each victory, it is true, in the first place brings about the results we expected, but in the second and third places it has quite different, unforeseen effects which only too often cancel the first. The people who, in Mesopotamia, Greece, Asia Minor and elsewhere, destroyed the forests to obtain cultivable land, never dreamed that by removing along with the forests the collecting centres and reservoirs of moisture they were laying the basis for the present forlorn state of those countries. When the Italians of the Alps used up the pine forests on the southern slopes, so carefully cherished on the northern slopes, they had no inkling that by doing so they were cutting at the roots of the dairy industry in their region; they had still less inkling that they were thereby depriving their mountain springs of water for the greater part of the year, and making it possible for them to pour still more furious torrents on the plains during the rainy seasons. Those who spread the potato in Europe were not aware that with these farinaceous tubers they were at the same time spreading scrofula. Thus at every step we are reminded that we by no means rule over nature like a conqueror over a foreign people, like someone standing outside nature – but that we, with flesh, blood and brain, belong to nature, and exist in its midst, and that all our mastery of it consists in the fact that we have the advantage over all other creatures of being able to learn its laws and apply them correctly.','The Part Played by Labour in the Transition from Ape to Man',1876);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Labour is the source of all wealth, the political economists assert. And it really is the source — next to nature, which supplies it with the material that it converts into wealth. But it is even infinitely more than this. It is the prime basic condition for all human existence, and this to such an extent that, in a sense, we have to say that labour created man himself.','The Part Played by Labour in the Transition from Ape to Man',1876);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','When we consider and reflect upon nature at large or the history of mankind or our own intellectual activity, at first we see the picture of an endless entanglement of relations and reactions in which nothing remains what, where and as it was, but everything moves, changes, comes into being and passes away. This primitive, naive but intrinsically correct conception of the world is that of ancient Greek philosophy, and was first clearly formulated by Heraclitus: everything is and is not, for everything is fluid, is constantly changing, constantly coming into being and passing away.  But this conception, correctly as it expresses the general character of the picture of appearances as a whole, does not suffice to explain the details of which this picture is made up, and so long as we do not understand these, we have not a clear idea of the whole picture. In order to understand these details we must detach them from their natural or historical connection and examine each one separately, its nature, special causes, effects, etc.','Anti-Dühring',1877);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Only sound common sense, respectable fellow that he is, in the homely realm of his own four walls, has very wonderful adventures directly he ventures out into the wide world of research.','Anti-Dühring',1877);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Nature is the proof of dialectics, and it must be said for modern science that it has furnished this proof with very rich materials increasing daily.','Anti-Dühring',1877);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','all past history was the history of class struggles; that these warring classes of society are always the products of the modes of production and of exchange.','Anti-Dühring',1877);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','the principles are not the starting-point of the investigation, but its final result; they are not applied to nature and human history, but abstracted from them, it is not nature and the realm of man which conform to these principles, but the principles are only valid in so far as they are in conformity with nature and history. That is the only materialist conception of the matter.','Anti-Dühring',1877);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Freedom does not consist in any dreamt-of independence from natural laws, but in the knowledge of these laws, and in the possibility this gives of systematically making them work towards definite ends.','Anti-Dühring',1877);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The idea that political acts, grand performances of state, are decisive in history is as old as written history itself, and is the main reason why so little material has been preserved for us in regard to the really progressive evolution of the peoples which has taken place quietly, in the background, behind these noisy scenes on the stage.','The Theory of Force',1877);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The history of the decline of primitive communities (it would be a mistake to place them all on the same level; as in geological formations, these historical forms contain a whole series of primary, secondary, tertiary types, etc.) has still to be written. All we have seen so far are some rather meagre outlines. But in any event the research has advanced far enough to establish that: (1) the vitality of primitive communities was incomparably greater than that of Semitic, Greek, Roman, etc. societies, and, a fortiori, that of modern capitalist societies; (2) the causes of their decline stem from economic facts which prevented them from passing a certain stage of development','Letter To Vera Zasulich',1881);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Not only can we manage very well without the interference of the capitalist class in the great industries of the country, but that their interference is becoming more and more a nuisance.','Social Classes - Necessary and Superfluous',1881);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Nature is the proof of dialectics, and it must be said for modern science that it has furnished this proof with very rich materials increasingly daily, and thus has shown that, in the last resort, Nature works dialectically and not metaphysically; that she does not move in the eternal oneness of a perpetually recurring circle, but goes through a real historical evolution.','Socialism: Utopian & Scientific',1880);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The materialist conception of history starts from the proposition that the production of the means to support human life and, next to production, the exchange of things produced, is the basis of all social structure; that in every society that has appeared in history, the manner in which wealth is distributed and society divided into classes or orders is dependent upon what is produced, how it is produced, and how the products are exchanged. From this point of view, the final causes of all social changes and political revolutions are to be sought, not in men’s brains, not in men’s better insights into eternal truth and justice, but in changes in the modes of production and exchange.','Socialism: Utopian & Scientific',1880);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','It is becoming equally imperative to bring the individual spheres of knowledge into the correct connection with one another. In doing so, however, natural science enters the field of theory and here the methods of empiricism will not work, here only theoretical thinking can be of assistance. But theoretical thinking is an innate quality only as regards natural capacity. This natural capacity must be developed, improved, and for its improvement there is as yet no other means than the study of previous philosophy.','On Dialectics',1878);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Dialectics constitutes the most important form of thinking for present-day natural science, for it alone offers the analogue for, and thereby the method of explaining, the evolutionary processes occurring in nature, inter-connections in general, and transitions from one field of investigation to another.','On Dialectics',1878);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The Greeks were not yet advanced enough to dissect, analyse nature — nature is still viewed as a whole, in general. The universal connection of natural phenomena is not proved in regard to particular; to the Greeks it is the result of direct contemplation. Herein lies the inadequacy of Greek philosophy, ... But herein also lies its superiority over all its subsequent metaphysical opponents. If in regard to the Greeks metaphysics was right in particulars, in regard to metaphysics the Greeks were right in general.','On Dialectics',1878);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','What is known as ‘Marxism’ in France is, indeed, an altogether peculiar product — so much so that Marx once said to Lafargue: ‘Ce qu’il y a de certain c’est que moi, je ne suis pas Marxiste.’ [If anything is certain, it is that I myself am not a Marxist]','Letter to Eduard Bernstein',1882);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Just as Darwin discovered the law of development or organic nature, so Marx discovered the law of development of human history: the simple fact, hitherto concealed by an overgrowth of ideology, that mankind must first of all eat, drink, have shelter and clothing, before it can pursue politics, science, art, religion, etc.; that therefore the production of the immediate material means, and consequently the degree of economic development attained by a given people or during a given epoch, form the foundation upon which the state institutions, the legal conceptions, art, and even the ideas on religion, of the people concerned have been evolved, and in the light of which they must, therefore, be explained, instead of vice versa, as had hitherto been the case.','Speech at the Graveside of Karl Marx',1883);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','It is precisely the alteration of nature by men, not solely nature as such, which is the most essential and immediate basis of human thought.','Dialectics of Nature',1883);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','It is, therefore, from the history of nature and human society that the laws of dialectics are abstracted. For they are nothing but the most general laws of these two aspects of historical development, as well as of thought itself.  And indeed they can be reduced in the main to three:  The law of the transformation of quantity into quality and vice versa;  The law of the interpenetration of opposites;  The law of the negation of the negation.','Dialectics of Nature',1883);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','It was Marx who had first discovered the great law of motion of history, the law according to which all historical struggles, whether they proceed in the political, religious, philosophical or some other ideological domain, are in fact only the more or less clear expression of struggles of social classes, and that the existence and thereby the collisions, too, between these classes are in turn conditioned by the degree of development of their economic position, by the mode of their production and of their exchange determined by it. This law, which has the same significance for history as the law of the transformation of energy has for natural science.','Preface to The Eighteenth Brumaire of Louis Bonaparte',1885);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The economic facts, which have so far played no role or only a contemptible one in the writing of history, are, at least in the modern world, a decisive historical force; that they form the basis of the origination of the present-day class antagonisms; that these class antagonisms, in the countries where they have become fully developed, thanks to large-scale industry, hence especially in England, are in their turn the basis of the formation of political parties and of party struggles, and thus of all political history. Marx had not only arrived at the same view, but had already, in the Deutsche-Französische Jahrbücher (1844), generalized it to the effect that, speaking generally, it is not the state which conditions and regulates the civil society at all, but civil society which conditions and regulates the state, and, consequently, that policy and its history are to be explained from the economic relations and their development, and not vice versa.','On the History of the Communist League',1885);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','Communism now no longer meant the concoction, by means of the imagination, of an ideal society as perfect as possible, but insight into the nature, the conditions and the consequent general aims of the struggle waged by the proletariat.','On the History of the Communist League',1885);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The doctrine of Hegel, taken as a whole, left plenty of room for giving shelter to the most diverse practical party views. And in the theoretical Germany of that time, two things above all were practical: religion and politics. Whoever placed the chief emphasis on the Hegelian system could be fairly conservative in both spheres; whoever regarded the dialectical method as the main thing could belong to the most extreme opposition, both in politics and religion.','Ludwig Feuerbach & the End of Classical German Philosophy',1886);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The great basic question of all philosophy, especially of more recent philosophy, is that concerning the relation of thinking and being. ...  The answers which the philosophers gave to this question split them into two great camps. Those who asserted the primacy of spirit to nature and, therefore, in the last instance, assumed world creation in some form or other — and among the philosophers, Hegel, for example, this creation often becomes still more intricate and impossible than in Christianity — comprised the camp of idealism. The others, who regarded nature as primary, belong to the various schools of materialism.','Ludwig Feuerbach & the End of Classical German Philosophy',1886);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','That which is willed happens but rarely; in the majority of instances the numerous desired ends cross and conflict with one another, or these ends themselves are from the outset incapable of realisation, or the means of attaining them are insufficient. thus the conflicts of innumerable individual wills and individual actions in the domain of history produce a state of affairs entirely analogous to that prevailing in the realm of unconscious nature.','Ludwig Feuerbach & the End of Classical German Philosophy',1886);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The only war left for Prussia-Germany to wage will be a world war, a world war, moreover of an extent the violence hitherto unimagined. Eight to ten million soldiers will be at each other’s throats and in the process they will strip Europe barer than a swarm of locusts. The depredations of the Years’ War compressed into three to four years and extended over the entire continent; famine, disease, the universal lapse into barbarism.','Introduction to Borkheim',1887);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','According to the materialist conception of history, the ultimately determining element in history is the production and reproduction of real life. Other than this neither Marx nor I have ever asserted. Hence if somebody twists this into saying that the economic element is the only determining one, he transforms that proposition into a meaningless, abstract, senseless phrase.','Letter to J Bloch',1890);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','To my mind, the so-called ‘socialist society’ is not anything immutable. Like all other social formations, it should be conceived in a state of constant flux and change. It’s crucial difference from the present order consists naturally in production organized on the basis of common ownership by the nation of all means of production. To begin this reorganization tomorrow, but performing it gradually, seems to me quite feasible. That our workers are capable of it is borne out by their many producer and consumer cooperatives which, whenever they’re not deliberately ruined by the police, are equally well and far more honestly run than the bourgeois stock companies.','Letter to Otto Von Boenigk',1890);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','The day when we are in the majority, what the French army did instinctively in not firing on the people will be repeated in our country quite consciously. Yes, whatever the frightened bourgeois say, we are able to calculate the moment when we shall have the majority of the people behind us; our ideas are making headway everywhere, as much among teachers, doctors, lawyers, etc. as among the workers. If we had to start wielding power tomorrow, we should need engineers, chemists, agronomists. Well, it is my conviction that we would have a good many of them behind us already. In five or ten years we shall have more of them than we need.','Interview with Le Figaro',1893);
INSERT INTO engels (author,quote,source,year) VALUES ('Friedrich Engels','What we understand by the economic conditions which we regard as the determining basis of the history of society are the methods by which human beings in a given society produce their means of subsistence and exchange the products among themselves (in so far as division of labour exists). Thus the entire technique of production and transport is here included. According to our conception, this technique also determines the method of exchange and, further, the division of products, ...','Letter to Starkenburg',1894);