USE quotes_db;

-- CREATE TABLE billhicks(
--     id INTEGER NOT NULL AUTO_INCREMENT
--     ,author VARCHAR(16)
--     ,quote VARCHAR(2048)
--     , PRIMARY KEY (id)
-- );

INSERT INTO quotes_db.billhicks (author, quote)
VALUES
('Bill Hicks','It’s just a ride.'),
('Bill Hicks','The world is like a ride in an amusement park.'),
('Bill Hicks','We are the facilitators of our own creative evolution.'),
('Bill Hicks','I don’t mean to sound bitter, cynical, but I know what’s going on in the world and I don’t like it.'),
('Bill Hicks','Today a young man on acid realized that all matter is merely energy condensed to a slow vibration.'),
('Bill Hicks','Life is only a dream, and we are the imagination of ourselves.'),
('Bill Hicks','Watching television is like taking black spray paint to your third eye.'),
('Bill Hicks','Go back to bed, America, your government is in control again.'),
('Bill Hicks','Mere existence is not enough. It’s all about the journey, man.'),
('Bill Hicks','What business is it of yours what I do, read, buy, see, or take into my body as long as I do not harm another human being on this planet?'),
('Bill Hicks','How about a positive LSD story? Wouldn’t that be newsworthy, just once?'),
('Bill Hicks','We all pay for life with death, so everything in between should be free.'),
('Bill Hicks','We are free to do as we are told.'),
('Bill Hicks','There is no such thing as death, life is only a dream, and we are the imagination of ourselves.'),
('Bill Hicks','The worst kind of non-smokers are the ones who come up to you coughing and hocking and breathing like a plague victim.'),
('Bill Hicks','What’s the point of a reptile government controlling the world if you’re still an asshole?'),
('Bill Hicks','It’s all about money, not freedom, y’all, okay? Nothing to do with fucking freedom.'),
('Bill Hicks','I’m not a conspiracy theorist. I’m a conspiracy analyst.'),
('Bill Hicks','It’s always funny until someone gets hurt, and then it’s just hilarious.'),
('Bill Hicks','All matter is merely energy condensed to a slow vibration.'),
('Bill Hicks','The whole image is that eternal suffering awaits anyone who questions God’s infinite love. That’s the message we’re brought up with, isn’t it?'),
('Bill Hicks','I believe there is an equality to all humanity. We all suck.'),
('Bill Hicks','We are the facilitators of our own creative evolution.'),
('Bill Hicks','I’m just trying to rid the world of all these fevered egos that are tainting our collective unconscious.'),
('Bill Hicks','We live in a world where John Lennon was murdered, yet Barry Manilow continues to put out albums.'),
('Bill Hicks','I don’t care if you’re Christian, Muslim, atheist, or Buddhist. Every group should be treated with respect and fairness.'),
('Bill Hicks','You know all the money we spend on nuclear weapons and defense each year? If we spent that money feeding and clothing the poor of the world, it would pay for it many times over.'),
('Bill Hicks','It’s called freedom of choice, and it’s wonderful. It’s just, you have to own your own responsibility to that choice.'),
('Bill Hicks','Music is a great energizer. It’s a language everybody knows.'),
('Bill Hicks','Next stop, apathy.'),
('Bill Hicks','Folks, it’s time to evolve. That’s why we’re troubled.'),
('Bill Hicks','I left in love, in laughter, and in truth, and wherever truth, love, and laughter abide, I am there in spirit.'),
('Bill Hicks','If you’re living for tomorrow, you’re always gonna be one day behind.'),
('Bill Hicks','It’s always the ones who don’t believe in drugs that try to convince you they’re great.'),
('Bill Hicks','I get tired of explaining the same basic points over and over.'),
('Bill Hicks','I’m tired of this back-slapping Isn’t humanity neat? bullshit. We’re a virus with shoes.'),
('Bill Hicks','The only good drug test is if you can hit the note in the song.'),
('Bill Hicks','There’s no such thing as death, life is just a dream, and we’re the imagination of ourselves.'),
('Bill Hicks','People are bringing shotguns to UFO sightings in Fife, Alabama. I think we’re confusing our roles here.'),
('Bill Hicks','I never got along with my dad. Kids used to come up to me and say, My dad can beat up your dad. I’d say, Yeah? When?'),
('Bill Hicks','A lot of Christians wear crosses around their necks. Do you think when Jesus comes back he ever wants to see a cross?'),
('Bill Hicks','I don’t do drugs anymore… than, say, the average touring funk band.'),
('Bill Hicks','You ever notice how people who believe in Creationism look really unevolved?'),
('Bill Hicks','People who hate people… come together!'),
('Bill Hicks','It’s not a war on drugs, it’s a war on personal freedom.'),
('Bill Hicks','I’ll show you politics in America. Here it is, right here. I think the puppet on the right shares my beliefs. I think the puppet on the left is more to my liking. Hey, wait a minute, there’s one guy holding out both puppets!'),
('Bill Hicks','My voice is gone from yelling and squealing and screaming.'),
('Bill Hicks','There are dick jokes, and then there are moments of revelation.'),
('Bill Hicks','What is it about drugs that make you feel good? They stop you from feeling bad.'),
('Bill Hicks','It’s great to be here. Really. For you.'),
('Bill Hicks','Why is marijuana against the law? It grows naturally upon our planet. Doesn’t the idea of making nature against the law seem a bit… unnatural?'),
('Bill Hicks','What are you reading for?'),
('Bill Hicks','We’re a virus with shoes.'),
('Bill Hicks','Laughter is one of the greatest therapies.'),
('Bill Hicks','Take away the right to say fuck and you take away the right to say fuck the government.'),
('Bill Hicks','I’ve watched things you people wouldn’t believe.'),
('Bill Hicks','You see, I think drugs have done some good things for us. I really do.'),
('Bill Hicks','I believe that God left certain drugs growing naturally upon our planet to help speed up and facilitate our evolution.');
