USE quotes_db;

CREATE TABLE billhicks(
    id INTEGER NOT NULL AUTO_INCREMENT
    ,author VARCHAR(16)
    ,quote VARCHAR(2048)
    , PRIMARY KEY (id)
);

INSERT INTO quotes_db.billhicks (author, quote)
VALUES
('Bill Hicks', 'The definition of black irony is Pro-lifers killing Doctors who do abortions.'),
('Bill Hicks', 'I get a kick out of being an outsider constantly. It allows me to be creative. I don’t like anything in the mainstream and they don’t like me.'),
('Bill Hicks', 'Oh sorry, I was taking life seriously.'),
('Bill Hicks', 'You see, I think drugs have done some good things for us. I really do. And if you don’t believe drugs have done good things for us, do me a favor. Go home tonight. Take all your albums, all your tapes and all your CDs and burn them. Cause you know what, the musicians that made all that great music that’s enhanced your lives throughout the years were rrreal fucking high on drugs. The Beatles were so fucking high they let Ringo sing a few tunes.'),
('Bill Hicks', 'People often ask me where I stand politically. It’s not that I disagree with Bush’s economic policy or his foreign policy, it’s that I believe he was a child of Satan sent here to destroy the planet Earth. Little to the left.'),
('Bill Hicks', 'I can’t watch TV longer than five minutes without praying for nuclear holocaust.'),
('Bill Hicks', 'Here is my final point. About drugs, about alcohol, about pornography and smoking and everything else. What business is it of yours what I do, read, buy, see, say, think, who I fuck, what I take into my body - as long as I do not harm another human being on this planet?'),
('Bill Hicks', 'not all drugs are good.. some of them are great'),
('Bill Hicks', 'There are essentially only two drugs that Western civilization tolerates: Caffeine from Monday to Friday to energize you enough to make you a productive member of society, and alcohol from Friday to Monday to keep you too stupid to figure out the prison that you are living in.'),
('Bill Hicks', 'I smoke. If this bothers anyone, I suggest you look around at the world in which we live and shut your fuckin mouth.'),
('Bill Hicks', '...I just want to be free of the fears and anxieties and the superstitions of religion. An "avenging GOD"? One who created Hell for those who don’t believe? I thought we were the perfect and holy children of GOD? How could any limits possibly be put upon us? Hell.. really? I’m sorry, but... no. Wrong. You’re wrong. That’s an insane GOD and therefore not mine. Because, see, GOD would be very sane, don’t you get it?'),
('Bill Hicks', 'I know this is not a very popular idea. You don’t hear it too often any more … but it’s the truth. I have taken drugs before and … I had a real good time. Sorry. Didn’t murder anybody, didn’t rape anybody, didn’t rob anybody, didn’t beat anybody, didn’t lose – hmm – one fucking job, laughed my ass off, and went about my day. Sorry. Now, where’s my commercial?'),
('Bill Hicks', 'I left in love, in laughter, and in truth, and wherever truth, love and laughter abide, I am there in spirit.'),
('Bill Hicks', 'Listen, the next revolution is gonna be a revolution of ideas.'),
('Bill Hicks', 'You ever noticed how people who believe in Creationism look really un-evolved? You ever noticed that? Eyes real close together, eyebrow ridges, big furry hands and feet. "I believe God created me in one day". Yeah, looks like He rushed it'),
('Bill Hicks', 'It’s all about money, not freedom, y’all, okay? Nothing to do with fuckin freedom. If you think you’re free, try going somewhere without fucking money, okay?'),
('Bill Hicks', 'It’s not a war on drugs, it’s a war on personal freedom. Keep that in mind at all times.'),
('Bill Hicks', 'I need my sleep. I need about eight hours a day, and about ten at night.'),
('Bill Hicks', 'I was walking through Central Park, and I saw an old man smoking. Nothing makes a smoker happier than to see an old person smoking. This guy was ancient, bent over a walker, puffing away. I’m like, "Duuude, you’re my hero! Guy your age smoking, man, it’s great." He goes, "What? I’m 28."'),
('Bill Hicks', 'I was over in Australia during Easter, which was really interesting. You know, they celebrate Easter the exact same way we do, commemorating the death and resurrection of Jesus by telling our children that a giant bunny rabbit … left chocolate eggs in the night. Now … I wonder why we’re fucked up as a race. I’ve read the Bible. I can’t find the word "bunny" or "chocolate" anywhere in the fucking book.'),
('Bill Hicks', 'You see, Jung had this idea of a Collective Unconscious which mankind shared... and I agree. But! I think this Collective Mind is supposed to be conscious, not unconscious! And that is our job as the Agents of Evolution to enlighten - to bring light into the dark corners of that Netherworld and thus awaken our Mind to Truth and complete the circle that was broken with the dream of our fall from Grace.'),
('Bill Hicks', 'How about a positive LSD story? Wouldn’t that be news-worthy, just the once? To base your decision on information rather than scare tactics and superstition and lies? I think it would be news-worthy. "Today, a young man on acid realized that all matter is merely energy condensed to a slow vibration. That we are all one consciousness experiencing itself subjectively. There is no such thing as death, life is only a dream and we’re the imagination of ourselves" . . . "Here’s Tom with the weather."'),
('Bill Hicks', 'Do you think magic mushrooms growing atop cow shit was an accident? Where do you think the phrase, ‘that’s good shit’ came from? Why do you think Hindus think cows are holy? Holy shit!'),
('Bill Hicks', 'I do not believe making money in order to consume goods is mankind’s sole purpose on this planet.'),
('Bill Hicks', 'Today I realized that all matter is merely energy condemned to a slow vibration. That we are all one consciousness experiencing itself subjectively, there is no such thing as death, life is only a dream, and we are the imagination of ourselves. Brothers and sisters, friends and neighbors, vibrations in the mind of the one true god, whose name is Love.'),
('Bill Hicks', 'Why is marijuana against the law? It grows naturally upon our planet. Doesn’t the idea of making nature against the law seem to you a bit... unnatural?'),
('Bill Hicks', 'The reason the world’s so fucked up is we’re undergoing evolution. And the reason our institutions, our traditional religions are all crumbling is because they’re no longer relevant'),
('Bill Hicks', 'I’m tired of this back-slappin’ isn’t humanity neat bullshit. We’re a virus with shoes.'),
('Bill Hicks', 'The idea of getting a, you know, syringe full of heroin and shooting it in the vein under my cock right now seems like almost a productive act.'),
('Bill Hicks', 'I loved when Bush came out and said, "We are losing the war against drugs." You know what that implies? There’s a war being fought, and the people on drugs are winning it.'),
('Bill Hicks', 'All governments are lying cocksuckers.'),
('Bill Hicks', 'There’s some serious pockets of humanity out there. Go to some of these truck stops in the middle of nowhere you’ll meet some serious folk. Order coffee the guy behind the counter goes "you want the 32 oz. or the large?" Shit, how big is that large? "You goin’ want to pull yer car round back, I goin start that pump." That sounds like a lot of coffee, dude. I don’t know if I want to be awake that long in Tennessee. On second thought give me that pussy size.'),
('Bill Hicks', 'Anybody can be a bum; all it takes is the right girl, the right bar and the right friends, and you are well… your buddies will see you off. They’ll christen your dumpster for you.'),
('Bill Hicks', 'We live in a world where John Lennon was murdered, yet Barry Manilow continues to put out fucking albums. God-dammit! If you’re gonna kill somebody, have some fucking taste. I’ll drive you to Kenny Rogers house.'),
('Bill Hicks', 'One time me and three friends dropped acid and drove around in my dad’s car. He has one of those talking cars, we’re tripping, and the car goes, "The door is ajar." We pulled over and thought about that for 12 hours. "How can a door be a jar?" … "Why would they put a jar on a car?" … "Oh man, the freeways melting!" … "Put it in the jar."'),
('Bill Hicks', 'They proved that if you quit smoking, it will prolong your life. What they haven’t proved is that a prolonged life is a good thing. I haven’t seen the stats on that yet.'),
('Bill Hicks', 'I think it’s interesting the two drugs that are legal, alcohol and cigarettes, two drugs that do absolutely nothing for you at all, are legal, and the drugs that might open your mind up to realize how badly you’re being fucked every day of your life? Those drugs are against the law. He-heh, coincidence? See, I’m glad mushrooms are against the law, cause I took em one time, and you know what happened to me? I laid in a field of green grass for four hours going, "My God! I love everything." Yeah, Now, if that isnt a hazard to our country... how are we gonna justify arms dealing if we know were all one?!'),
('Bill Hicks', 'Dinosaur fossils? God put those here to test our faith." I think God put you here to test my faith, dude. Does that bother anybody else—the idea that God might be … fucking with our heads? I have trouble sleeping with that knowledge. Some prankster God running around, [pantomimes digging] "We’ll see who believes in Me now! I am the Prankster God. I am killing Me!"'),
('Bill Hicks', 'They lie about marijuana. Tell you pot-smoking makes you unmotivated. Lie! When you’re high, you can do everything you normally do just as well—you just realize that it’s not worth the fucking effort. There is a difference.'),
('Bill Hicks', 'I believe that the Bible is the literal word of God." And I say no, it’s not, Dad. "Well, I believe that it is." Well, you know, some people believe they’re Napoleon. That’s fine. Beliefs are neat. Cherish them, but don’t share them like they’re the truth.'),
('Bill Hicks', 'The Greeks used to put a lot of bodily functions in their plays, and a lot of graphic sexual material, because they believed, that in performing that way it released the demons of shame from the audience, which is what I believe. Cuz I think we’re all pretty much the same, and we all have grown up with that shame-based thing that America deals with, right? And to sit there and hear someone talk about their love of having sex, whatever, makes you feel like you’re not alone, with what you think maybe are dark, twisted thoughts, cuz they’re not. We all share these thoughts. So that’s why I talk like I do, or did, before I retired tonight.'),
('Bill Hicks', 'I’ll show you politics in America. Here it is, right here. "I think the puppet on the right shares my beliefs." "I think the puppet on the left is more to my liking." "Hey, wait a minute, there’s one guy holding out both puppets!" "Shut up! Go back to bed, America. Your government is in control. Here’s Love Connection. Watch this and get fat and stupid. By the way, keep drinking beer, you fucking morons."'),
('Bill Hicks', 'There’s a new party being born: The People Who Hate People Party. People who hate people, come together! "No!" We’re kind of having trouble getting off the boards, you know. Come to our meeting! "Are you gonna be there?" Yeah. "Then I ain’t fucking coming." But you’re our strongest member! "Fuck you!" That’s what I’m talking about, you asshole. "Fuck off!" Damn, we almost had a meeting going. It’s so hard to get my people together.'),
('Bill Hicks', 'I hate patriotism. I can’t stand it, man — makes me fuckin sick. It’s a round world last time I checked.'),
('Bill Hicks', 'That’s what I hate about the war on drugs. All day long we see those commercials: "Here’s your brain, here’s your brain on drugs", "Just Say No", "Why do you think they call it dope?" … And then the next commercial is [singing] "This Bud’s for yooouuuu." C’mon, everybody, let’s be hypocritical bastards. It’s okay to drink your drug. We meant those other drugs. Those untaxed drugs. Those are the ones that are bad for you.'),
('Bill Hicks', 'Pot is a better drug than alcohol. Fact! … I’ll prove it to you. If you’re at a ball game or a concert and someone’s really violent and aggressive and obnoxious, are they drunk or are they smoking pot? [The crowd answers "Drunk."] Wow! We all know the truth.');
