
INSERT INTO quotes_db.tpb (author, quote)
VALUES
('Bubbles','I’d like to see that Red Blue Green cocksucker put one of those together fucking duct taping it.'),
('Bubbles','Dino. Did you call Fred and Barney too? How about Mr. Slate?'),
('Bubbles','I won’t tell anyone you have splinters in your lips if you don’t tell anyone I have a wooden cock.'),
('Bubbles','Randy: Does that thing really launch, Bubbles? Bubbles: Does the Tin Man have a sheet-metal cock?'),
('Bubbles','Julian, what’s a shit hawk? Is it some kind of shitty bird that swoops down and puts poop on you?'),
('Bubbles','Ricky, what happened to your fucking eyes? You look like Alice Cooper?'),
('Bubbles','(in reference to the Helix song Rock You) I’m not giving anyone a fucking R!'),
('Bubbles','Ricky, those laws are there to protect kids, not so goofballs like you can put them in the car with no door on it, and drive around the fuckin’ neighbourhood stealin’ barbecues!'),
('Bubbles','Can I come out now? I think I have a leech on my bird.'),
('Bubbles','Julian, we’re both baked. That’s why were probably not making any sense.'),
('Bubbles','No, he’s just a really big kitty, and he’s baked!'),
('Bubbles','Bubbles: Stealing gas? Why, Cory and Trevor, that’s highly illegal, you shouldn’t be stealing gas, Cory and Trevor.'),
('Bubbles','(Rapping) I got a grey kitty, white one, and a tabby too/ And a big orange guy who put snakes in my shoes/ Mad MC skills, leave ya struck, and I roll with ma kitties, and I’am hard as fuck/ I am down with Plato and Socrates/ And I like to get busy with all the ladies. Grunt, grunt/ sumthin,’ sumthin,’ sumthin,’/ Grunt/ Up in ma shed, up in ma shed...'),
('Bubbles','Holy fuck boys, this shed is like a fucking palace! Indoor plumbing (toilet seat inside), satellite tv, 400 channels, anything I wanna watch, it’s right there, space for my kitties, Mobile phone, new technology (holds up an ancient mobile phone), this is the best fucking shed there ever was!'),
('Bubbles','Here, Cory-Trevor, Cory-Trevor!'),
('Bubbles','Hampton: Can you read, my son? Bubbles: Well, that depends, can you go fuck yourself?'),
('Bubbles','Trevor: Julian, this looks like a pirate gun. Bubbles: Well Trevor, I guess that makes you Long John Dickweed, then.'),
('Bubbles','Green Bastard, from parts unknown (grunts and inhales).'),
('Bubbles','Lahey, can you please get the flyin’ fuck out of our way!'),
('Bubbles','COCK-SUCKER!'),
('Bubbles','There’s a note pinned to a tree! Diddly-dee!'),
('Bubbles','(To Randy re: cheeseburgers) How many did you drive into that big fuckin cheeseburger-locker?'),
('Bubbles','Well, when I was a little guy, I always wanted to go up into space, be a space-man. But you gotta be able to see really fuckin good to do that job. Some guy would take one look at me and say Uhhh, sorry sir, you gotta be able to see a little better than you... I don’t give a fuck.'),
('Bubbles','Holy sweet flying fuck!'),
('J-Roc','There’s 2 things mafukas gonna know about J-to-the-ROC: I spin more rhymes than a lazy Susan, and I’m innocent until mah guilt is proven! Peace! Representin’ Sunnyvale, straight-the-fuck-up.'),
('J-Roc','(To Lahey and Randy) Why don’t you run along, Gut Cassidy and the Sundance Cheeseburger. Don’t look into my eyes like I got candy for you.'),
('J-Roc','Only wacksuckas like Cory and Trevor steal gas...and deal dope.'),
('J-Roc','Yo Julian, I’m going to be a daddy. Not once but two times dawg, two times.'),
('J-Roc','You know what I’m sayin?'),
('J-Roc','Rayyyyy - Kojak’s got a wig on, RAYYY!'),
('J-Roc','So why don’t you move it along, you Rico-Suave-lookin mafucka, cuz you ain’t beatin nobody.'),
('J-Roc','You mean we can’t go on with the game cuz some mafucka can’t go to Canadian Mafacka (Tire) and get a new orange mafucka (ball) for $2.99? That’s wack, Jules.'),
('J-Roc','Yo, it’s Rocky and Bullma’fucker.'),
('J-Roc','J-Roc an’ da Rock-Pile ALL UP IN DIS MA !'),
('J-Roc','Naw, man, I don’t play guns, mafucka.'),
('J-Roc','We ain’t down with killin, we down with chillin. Peace!'),
('J-Roc','The day J-ROC loses his flow, is the day the hair on Jim Lahey’s bald head grow!'),
('J-Roc','(referring to Jacob) That’s the fuckin law bitch from the grocery store y’man, who you pointin at, skeleton?'),
('J-Roc','This is BULL-ISH!'),
('J-Roc','I can’t even breathe up in this piece!'),
('J-Roc','(to Randy) Oh what, you ain’t pregnant with a bucketa chicken?'),
('J-Roc','(to Randy) What you talkin' 'bout, you inflatable Elvis?'),
('J-Roc','Oh, no, you din’t just call me Jamie!'),
('J-Roc','(holding his chains to Randy’s gut like a stethoscope) I hear chicken. I hear cola fizz, and mustard and relish coagulating together with french fries and onion rings, but you know what? I don’t hear a heart.'),
('J-Roc','Carpe Dizem!'),
('Lahey','When you plant shit-seeds, you get shit-weeds'),
('Lahey','Birds of a shitfeather flock together, Randy'),
('Lahey','We’re in the eye of a shiticane here, Julian, and Ricky’s a low-shit system!'),
('Lahey','Shit-storm troopers'),
('Lahey','The shit-apple doesn’t fall far from the shit-tree'),
('Lahey','Captain Shittacular'),
('Lahey','I’m watching you like a shithawk'),
('Lahey','We’re sailing into a shit-typhoon Randy, we’d better haul in the jib before it gets covered in shit'),
('Lahey','When you’re getting pelted with shitballs, deputy, you gotta get a shit-bat'),
('Lahey','The shit pool’s gettin full, Randy, time to strain the shit before it overflows. I will not have a Pompeiian catastrophie happening in Sunnyvale'),
('Lahey','How dare you involve my daughter in your hemisphere of shit?'),
('Lahey','Your shit-goose is cooked, Ricky'),
('Lahey','Shit-apples never fall far from the shit-tree'),
('Lahey','He’s about to enter the shit-tornado to Oz'),
('Lahey','Do you know what a shit-rope is Julian? It’s a rope covered in shit that criminals try to cling to. Y’see, the shit acts like grease, and the harder you tighten your grip, the more you slide down it'),
('Lahey','A shit-leopard can’t change its spots'),
('Lahey','We need more shit puppets for our play, Randy, and we need angry shit puppets but they aren’t mad at us. Shit puppets only get angry at other shit puppets'),
('Lahey','Randy: Cops and dope don’t mix, do they Mr. Lahey? Lahey: Like shit and strawberry shortcake Randy'),
('Lahey','I live by the golden rule: if you don’t cross my shitline I won’t cross yours. But when Ray told everybody in the park that I was drinking again, he crossed the goddamn shitline'),
('Lahey','Lahey: Do you know what a shit barometer is, Bubbles? Measures the shit pressure in the air. You can feel it. Listen, Bubs. You hear that? The sounds of the whispering winds of shit? You can hear it'),
('Lahey','Do you feel that, Randy, the way the shit clings to the air? Shit Blizzard'),
('Lahey','Never Cry Shitwolf'),
('Lahey','Did you see that Randy, Goddamn shitapple driving the shitmobile. Nobody else in this park gives a fuck, why should I?'),
('Lahey','Lahey -You know what’s at work here, it’s shit tectonics, when two shit plates strike and come together under incredible pressure, do you know what happens, Bubbles?'),
('Lahey','Yes I used to drink, Randy, but I got the shitmonkey off my back for good'),
('Lahey','You just opened Pandora’s Shitbox, Ray'),
('Lahey','You know what you get when two shit-tectonic plates collide? Shitquakes, Julian. Shitquakes'),
('Lahey','The ole shit liner is coming to port, and I’ll be there to tie her up'),
('Lahey','Y’see, Ricky started off as a little shitspark from the ol shitflint that eventually grew into a shitbonfire, and driven by the winds of his monumental ignorance, grew into a raging shitfirestorm. If I marry Barb, I’ll have total control of Sunnyvale, and then I’ll be able to unleash a shitnami tidal wave that will extinguish Ricky and his shitflames forever. And with any luck, he’ll drown in the undershit of that wave...shitwaves'),
('Lahey','Tic Toc, Shit clock’s tickin Rick'),
('Lahey','We got the key to shitty city, Ran, and Julian’s the muscular mayor'),
('Lahey','You boys have loaded up a hair-trigger, double barrelled shitmachinegun, and the barrel’s pointing right at your own heads'),
('Lahey','Shit flowers, Randy. From a distance they look like ordinary flowers, but when you get right down and stick your nose in them you realize they’re shit flowers, and there’s a whole fucking bouquet down there right in front of Ray’s trailer'),
('Lahey','Lahey: Shit moths, Randy. Randy: Is that you or the liquor speaking, Mr Lahey?'),
('Lahey','Hey Sexian (Lahey adressing Julian)'),
('Lahey','Whenever I’m sober, the boys are careful, they’re scared of me cause they know what I’ll do. They’re cautious, it’s hard to catch them. But when I’m drinking, their shitguards are down and they fuck up, but the problem is when I’m drinking, I fuck up too, a lot, Barb. I gotta be drinking, but not drinking, ya see? The only way to do that, is to pretend, I am gonna pretend to be drunk, collect evidence and build a solid case against them. Sober as a judge I’m gonna show up today at the cheeseburger picnic, and I’m gonna pretend to be a drunken idiot. And why? Shitguards, Barb...shitguards'),
('Lahey','This place is a dump. You have my permission to do whatever you want, any time any place, and you don’t have to listen to Pilsbandy Doughboy (Randy) or Team Sexy (the police)'),
('Ricky','Lucy is banging cops which is no big deal, I guess. I don’t run Lucy. She’s for to be her own woman (free to be)'),
('Ricky','Lucy might have a problem, but what Lucy doesn’t know won’t learn her. (hurt)'),
('Ricky','Get me two bags of chips: Dressed All Over, and Zesty Mordant. (All Dressed and Zesty. Mordant is French for Zesty and is a mix-up of reading both languages on the bilingual packaging in Canada)'),
('Ricky','Yeah, get me some ja-LAP-ano chips (jalapeño)'),
('Ricky','Worst case Ontario... (scenario)'),
('Ricky','It’s basically Peach’n’Cake (a piece of cake)'),
('Ricky','Denial and Error... (trial)'),
('Ricky','Make my words (Mark)*'),
('Ricky','Hey Bubs, are you watching that documentary on Saskatchewans?(Sasquatches)*'),
('Ricky','(While addressing the Judge in court) Thank you, Your Majesty. (Honour, which is still incorrect. In Canada a female judge is referred to as My Lady.)'),
('Ricky','I’m trying to try here, Sarah.'),
('Ricky','Who’s playing the pianio? (piano)'),
('Ricky','Make like a tree and fuck off. (leave)'),
('Ricky','I’m not the kind of person to say atodaso, but you know what? Atodaso, I-fucking-atodaso. (I told you so)'),
('Ricky','It was golfing flames, flames just golfing, golfing. (engulfed in flames)'),
('Ricky','It’s a Catch-23 situation. (Catch-22)'),
('Ricky','(To Alex Lifeson of Rush) Well, play that Diane Sawyer song, then. (Tom Sawyer - Rush song)'),
('Ricky','Looks like a tropical earthquake blew through here. (storm)'),
('Ricky','We can get 2 birds stoned at once. (kill 2 birds with one stone)'),
('Ricky','Why do you look like Indianapolis Jones? (Indiana)'),
('Ricky','He passed with flying fucking carpets. (colours)'),
('Ricky','It doesn’t take rocket appliances. (science)'),
('Ricky','Trinity’s at the age where it’s gorilla see gorilla do. (monkey)'),
('Ricky','Do you got a search warranty for that? (warrant)*'),
('Ricky','I must be fire retarded or something. (retardant)'),
('Ricky','I’m not a pezmist, I’m an optometrist. (Pessimist, Optimist)'),
('Ricky','These plates got me from Tuscany, Arizona to Kentville, Nova Scotia. (Tucson) - Ray, Ricky’s Dad'),
('Ricky','I’ll drive you back to the park, Lucy, but there is probably a pretty good chance that it might be over between us (Ricky uses a triple conditional; just one would be sufficient)'),
('Ricky','If my dad and Julian and Bubbles hadn’t had been out all night getting lap-dances and getting drunk, the whole thing could have been preventative. (prevented)'),
('Ricky','To be honest with you, I fucking hate bagminten. (badminton)'),
('Ricky','Breaker, Breaker, come in earth. This is Rocketship 27, some aliens fucked over the carbinator in engine number four, we are going to try to refuckulate it and land on Juniper. (carburetor, repair, Jupiter)'),
('Ricky','That’s not a ladybug. It’s a cannerpillar. (caterpillar)'),
('Ricky','...how to get Buhurbon stains out of Kahayki pants (Bourbon, Khaki)'),
('Ricky','One man’s garbage is another man person’s good ungarbage. (One man’s garbage is another man’s treasure)'),
('Ricky','Au gratin (gratis, free; au gratin is with cheese)'),
('Ricky','I-surance (Insurance)*'),
('Ricky','Swallow my prize (pride)'),
('Ricky','Neither here, there, or everywhere (Neither here nor there)'),
('Ricky','Boys, let’s make toast (Let’s make a toast)'),
('Ricky','There’s no lurches in there, Bubbles, is there? (leeches)'),
('Ricky','I know what you’re doing, Lahey, you’re trying to fill my feet. (fill my shoes)'),
('Ricky','You gotta remember, every kid goes through phrases. (phases)'),
('Ricky','What Julian don’t grow won’t burn him. (know, hurt)'),
('Ricky','Nice decnals! (decals)'),
('Ricky','I’m just stretched out! (stressed)*'),
('Ricky','I don’t need your cherry trees. (charity)*'),
('Ricky','What if he has radies? (rabies)'),
('Ricky','Supply and command. (demand)'),
('Ricky','What comes around is all around (What goes around comes around)'),
('Ricky','What, do you own space? No. Nay-saw does. (NASA)'),
('Ricky','Do unto others as you do unto you. (Do unto others as you would have them do unto you)'),
('Ricky','One day I will go somewhere that is hot, like Majaica or the Dromedary Republic (Jamaica, Dominican Republic)'),
('Ricky','Trinity made a life-ing thing basically out of this chicken. Started with a little eggy thing, and heated it up under these incu-baker things, and it...it was bornt. (living, incubator, born)'),
('Ricky','We’ll split 50/50/50. (three ways.)'),
('Ricky','(To Trevor and Cory) Well, I’d like for you two to come with us, but apparently it’s clear to see who makes the pants here. (wears the pants)'),
('Ricky','I hate to have to give you an ultimarium (ultimatum)'),
('Ricky','It’s me or Gumby and Pifuckio (Cory and Trevor)'),
('Ricky','Raykins! That’s what they are, Julian, fuckin raykins! (raccoons)'),
('Ricky','I’m not working for J-Roc, that’s against my vice principals (principles)'),
('Ricky','Bubbles, I don’t want any rich peopleman’s food, I want some fuckin meat that’s cooked. (people’s)'),
('Ricky','It’s survival of the fitness, boys. (fittest)'),
('Ricky','If Randy thinks he’s smartener than me, he’s wrong. (smarter)*'),
('Ricky','You gotta do illegal things once in a while, and then maturinate into a better person. (mature)'),
('Ricky','Your thoughts might be better than mine, but I have thoughts going around in my head too, about...different thinkings...about brain things that you can use and...doing different things.'),
('Ricky','Sweet empowered chicken things (sweet and sour chicken)'),
('Ricky','(To Shitty Bill) Take a shower for fuck’s sake! You look like a fuckin hobolo! (hobo)'),
('Ricky','(To Randy) Why don’t you fuck off and go get some hypo-suction! (liposuction)'),
('Ricky','It was my mother’s mating name. (maiden name)'),
('Ricky','Holy shit, you got us a lemon-zine? (Limousine)'),
('Ricky','Randy bornt my baby. (Randy is the father of Lucy’s 2nd child)'),
('Ricky','Lucy, I will make you have a eternity test. (paternity)'),
('Ricky','He’s gettin all frustated. (frustrated)'),
('Ricky','You can go to college and get your little Pf.D, or whatever the fuck it’s called! (Ph.D.)'),
('Ricky','Child reports (Child Support)'),
('Ricky','Get us the fuckin land papers A.S.A.T! (Land papers because he couldn’t pronounce ’topographic map, A.S.A.P)'),
('Ricky','I’m fucked over from being electromecuted! (electrocuted)'),
('Ricky','Those them cigarettes in there is our lifes! (are our lives)'),
('Ricky','...it’s distraculating my case. (distracting)'),
('Ricky','Amernicans! (Americans)'),
('Ricky','I have responsibles now... (Responsibilities)'),
('Ricky','Well, now we gotta go to the library and get a book on horficulture. (Horticulture)'),
('Ricky','I self-learned myself. (self-taught)');
